sudo: "required"
language: generic

# Tells Travis we require Docker
services:
  - docker

# Series of setup before running test, deploying, etc.
before_install:
  - docker build -t mrmasson/react-test -f ./client/Dockerfile.dev .

# Command required to run the test suites
# Travis CI will watch output of each command. If it returns something
# else then 0, it assume a fail.
script:
  - docker run -e CI=true mrmasson/react-test npm run test -- --coverage

# On test success, build production images
after_success:
  - docker build -t mrmasson/complex-nginx ./nginx
  - docker build -t mrmasson/complex-client ./clent
  - docker build -t mrmasson/complex-server ./server
  - docker build -t mrmasson/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to dockerhub
  - docker push mrmasson/complex-nginx
  - docker push mrmasson/complex-client
  - docker push mrmasson/complex-server
  - docker push mrmasson/complex-worker
